name: Upload Artifact

on:
  workflow_run:
    workflows: ["Build and Archive Artifact"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ needs.build.outputs.artifact_name }}
        path: artifacts/
      
    - name: Set up Git
      run: |
        git config user.email "2222076@slu.edu.ph"
        git config user.name "JUNE BRIAN SANONE"

    - name: Commit and push artifacts
      run: |
        git add .
        git commit -m "Deploy artifact: ${{ env.ARTIFACT_NAME }}"
        git push origin main
