name: Upload Artifact

on:
  workflow_run:
    workflows: ["Build and Archive Artifact"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ github.event.workflow_run.id }}-archive-${{ needs.archive.outputs.ARTIFACT_NAME }}
        path: artifacts/
      
    - name: Commit and push artifacts
      run: |
        git config user.email "2222076@slu.edu.ph"
        git config user.name "JUNE BRIAN SANONE"
        git add .
        git commit -m "Deploy artifact: ${{ env.ARTIFACT_NAME }}"
        git push origin main
