name: 2. Archive and Download Artifacts

on:
  workflow_run:
    workflows: ["1. Test Project"]
    types:
      - completed

jobs:
  archive:
    name: Archive into artifact
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Set artifact name
      id: set_artifact_name
      run: echo "ARTIFACT_NAME=finals-art-${{ github.run_number }}" >> $GITHUB_ENV
      
    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: src/
  
  download:
    name: Download artifact for testing
    runs-on: ubuntu-latest
    needs: archive

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.archive.outputs.ARTIFACT_NAME }}

    - name: Test artifact
      run: ls -R
